#include <json_edit_config.h>
#include <fingerprint_leb.h>
#include <networking_config.h>
#include <screen_compo.h>
#include <sd_edit_config.h>
#include <telegram.h>
#include <time_config.h>
#include <web_server_lis.h>
json_edit_config configC;
screen_compo screen;